filter:
    excluded_paths:
        - 'test/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
tools:
    external_code_coverage: true
